## About Jupyter Notebooks

Jupyter Notebooks are interactive coding environments, hosted as a webpage. They use various "Kernels" which support just about every programming language you can think of. **Ju**-**Py**-te-**R** is a name in reference to the core, supported, languages – Julia, Python, and R.

For this semester, we'll be using **Python**, supported by the iPython Kernel.

## Working through the notebook
You'll notice that all "code cells" (as they're called in Jupyter) are laid out in a repetitive fashion:
```python
here = "we have some code"
there = "are some snippets of code you shouldn't edit"
### START CODE HERE ###
but_here = "is a snippet you should edit"

if especially:
  for idx in range(None):
    # because this will throw an error
### END CODE HERE ###
```

To actually execute these code cells, you have two options:
1.  pressing &lt;shift&gt; + &lt;enter&gt;, or...
2.  clicking "Run Cell" in the toolbar of the notebook.

<div class="alert alert-warning" markdown=1>
**NOTE:** We'll typically specify `(~X lines of code)` in comments; **_this is an estimate_** so it shouldn't concern you if your code is longer or shorter that what `X` is stated to be.
</div>

---
<div class="alert alert-info" markdown=1><h2> Exercise 1 </h2></div>

Set test to any string of characters you want in the cell below to print that string, and run the two cells below. For example, if we were to set test to `"I love Python!"`, the expected output would be ```test: I love Python!```. It can be something creative or a reference to something. Just, please, make sure it isn't inappropriate.

In [1]:
### START CODE HERE ### (~1 line of code)
mytext = "I Love Python!"
### END CODE HERE ###

In [2]:
print("test: " + mytext)

test: I Love Python!


<div class="alert alert-success">Congratulations! You have just run your first two cells of python code using a Jupyter Notebook! :)</div>

<div class="alert alert-danger" markdown=1>
    <p>**What you need to remember:**</p>
    <ul>
        <li>Run your cells using &lt;shift&gt; + &lt;enter&gt; (or "Run cell")</li>
        <li> Write / edit / modify code in the designated areas only </li>
        <li> **Do not modify the code outside of the designated areas.**(This will likely result in a lower grade, or longer turn-around times on grading.) </li>
    </ul>
</div>

---
---

# Intro to Python, featuring `NumPy`

Here, your assignment begins. The goal is to give you a brief introduction to Python. (Even if you're intimately familiar, please execute all the steps outlined below.)

**Instructions:**
- Use Python on your own computer.
- `for` and `while` loops are heavily discouraged, unless absolutely necessary.
- We'll follow each code-cell with its expected output, so you can check your code. (**i.e. check your output! :)**)

**After this assignment you will:**
- Have an understanding of Jupyter Notebooks, using the iPython Kernel
- Have an understanding of `NumPy` functions as well as some of `NumPy`'s Linear Algebra operations (matrix / vector addition and multiplication)
- Understand what "broadcasting" means
- Have an affininty for vectorized code (it runs much more quickly)

Let's get started!

---
## 1 - Building basic functions with `NumPy`

> `NumPy` is the fundamental package for scientific computing with Python.
>
> &ndash; taken from Numpy website

Here, we'll cover several core `numpy` functions, e.g. `np.exp`, `np.log`, and `np.reshape`. Knowledge of these functions is integral to your success in future assignments.

---

### 1.1 - The Sigmoid function, `np.exp` ###

We'll take you through a comparison of `np.exp` and `math.exp`, to showcase why `np.exp` is preferable to `math.exp`. (Side note: `math` is Python's built-in math library, NumPy contains nearly all, if not all, of the functions within Python's `math` library.)

<div class="alert alert-info" markdown=1><h2> Exercise 2 </h2></div>

Build a function that returns the sigmoid of a real number `x`. In your sigmoid function implementation, use `math.exp()`.

**Recall**:
$sigmoid(x) = \frac{1}{1+e^{-x}}$ is sometimes also known as the logistic function. It is a non-linear function used not only in Machine Learning (Logistic Regression), but also in Deep Learning.

<img src="images/Sigmoid.png" style="width:500px;height:228px;">

To refer to a function belonging to a specific package you could call it using `<package_name>.<function>`. Implement and run the code below to see an example with `math.exp`.

In [3]:
# GRADED FUNCTION: basic_sigmoid
import math

def basic_sigmoid(x):
    """
    Compute sigmoid of x.

    Arguments:
    x -- A scalar

    Return:
    s -- sigmoid(x)
    """
    
    ### START CODE HERE ### (~1 line of code)
    s = 1 / (1 + (math.exp(-x)))
    ### END CODE HERE ###
    
    return s

In [4]:
basic_sigmoid(3)

0.9525741268224334

**Expected Output**: 

```python
basic_sigmoid(3) # 0.9525741268224334
```

Actually, we rarely use the `math` library in deep learning because the inputs of the functions are real numbers. In deep learning we mostly use matrices and vectors. This is why numpy is more useful. 

In [6]:
### One of many reasons we use `numpy` over `math` in machine learning
x = [1, 2, 3]
basic_sigmoid(x) # this will output an error, because x is a vector instead of a scalar

TypeError: bad operand type for unary -: 'list'

In fact, if $ x = (x_1, x_2, ..., x_n)$ is a row vector then `np.exp(x)` will apply the exponential function to every element of x. The output will thus be: `np.exp(x)` $= (e^{x_1}, e^{x_2}, ..., e^{x_n})$

In [7]:
import numpy as np

# example of np.exp
x = np.array([1, 2, 3])
print(np.exp(x)) # results: [exp(1), exp(2), exp(3)]

[ 2.71828183  7.3890561  20.08553692]


As learned in Linear Algebra courses, if `x` is a vector (`np.array`), then an operation like `x + 3`, or `x = 1 / x` will produce an output vector of the same dimensionsn as `x`.

In [8]:
# example of vector operation
x = np.array([1, 2, 3])
print(x + 3)

[4 5 6]


Any time you need more info on a numpy function, we encourage you to look at [the official documentation](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.exp.html). 

You can also create a new cell in the notebook and write `np.exp?` (for example) to get quick access to the documentation.

<div class="alert alert-info" markdown=1><h2> Exercise 3 </h2></div>

Implement the sigmoid function using `numpy`. 

**Instructions**: 
`x` now has the freedom to be a real number, vector, or matrix. The data structures we use in `numpy` to represent these shapes (vectors, matrices...) are called numpy arrays (`np.array`). (We'll elaborate on this in due time.)
$$ \text{For } x \in \mathbb{R}^n \text{,     } sigmoid(x) = sigmoid\begin{pmatrix}
    x_1  \\
    x_2  \\
    ...  \\
    x_n  \\
\end{pmatrix} = \begin{pmatrix}
    \frac{1}{1+e^{-x_1}}  \\
    \frac{1}{1+e^{-x_2}}  \\
    ...  \\
    \frac{1}{1+e^{-x_n}}  \\
\end{pmatrix}\tag{1} $$

In [9]:
# GRADED FUNCTION: sigmoid

import numpy as np # this means you can access numpy functions by writing np.function() instead of numpy.function()

def sigmoid(x):
    """
    Compute the sigmoid of x

    Arguments:
    x -- A scalar or numpy array of any size

    Return:
    s -- sigmoid(x)
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    s = 1 / (1 + np.exp(-x))
    ### END CODE HERE ###
    
    return s

In [10]:
x = np.array([1, 2, 3])
sigmoid(x)

array([0.73105858, 0.88079708, 0.95257413])

**Expected Output**: 

```python
array([0.73105858, 0.88079708, 0.95257413])
```

---
### 1.2 - Sigmoid gradient

To perform backpropagation, it's necessary we compute the gradients – here, we'll code-up your first gradient function.

<div class="alert alert-info" markdown=1><h2> Exercise 4 </h2></div>

Implement the function sigmoid_grad() to compute the gradient of the sigmoid function with respect to its input x. The formula is: $$sigmoid\_derivative(x) = \sigma'(x) = \sigma(x) (1 - \sigma(x))\tag{2}$$
You often code this function in two steps:
1. Set s to be the sigmoid of x. You might find your sigmoid(x) function useful.
2. Compute $\sigma'(x) = s(1-s)$

In [11]:
# GRADED FUNCTION: sigmoid_derivative

def sigmoid_derivative(x):
    """
    Compute the gradient (also called the slope or derivative) of the sigmoid function with respect to its input x.
    You can store the output of the sigmoid function into variables and then use it to calculate the gradient.
    
    Arguments:
    x -- A scalar or numpy array

    Return:
    ds -- Your computed gradient.
    """
    
    ### START CODE HERE ### (≈ 2 lines of code)
    s = 1 / (1 + np.exp(-x))
    t = (1 - s)
    ds = s * t
    ### END CODE HERE ###
    
    return ds

In [13]:
x = np.array([1, 2, 3])
print ("sigmoid_derivative([1, 2, 3]) = " + str(sigmoid_derivative(x)))

sigmoid_derivative([1, 2, 3]) = [0.19661193 0.10499359 0.04517666]


**Expected Output**: 

```python
sigmoid_derivative([1, 2, 3]) # [ 0.19661193  0.10499359  0.04517666]
```

---
### 1.3 - Reshaping arrays ###

Two common numpy functions used in machine learning are [`np.shape`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html) and [`np.reshape`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html). 
- `X.shape` is used to get the shape (dimension) of a matrix/vector `X`. 
- `X.reshape(...)` is used to reshape `X` into some other dimension. 

For example we represent images with 3D arrays of shape $(length, height, depth = 3)$. However, when actually using such an image as iniput to an algorithm... we convert the dimensions to $(length*height*3, 1)$. In other words, we "unroll", or `reshape`, the 3D array into a 1D vector.

<img src="images/image2vector_kiank.png" style="width:500px;height:300;">

<div class="alert alert-info" markdown=1><h2> Exercise 5 </h2></div>

Implement `image2vector()` that takes an input of shape (length, height, 3) and returns a vector of shape (length\*height\*3, 1). For example, if you would like to reshape an array v of shape (a, b, c) into a vector of shape (a*b,c) you would do:

``` python
v = v.reshape((v.shape[0]*v.shape[1], v.shape[2])) # v.shape[0] = a ; v.shape[1] = b ; v.shape[2] = c
```
- Please don't hardcode the dimensions of image as a constant. Instead look up the quantities you need with `image.shape[0]`, etc. 

In [14]:
# GRADED FUNCTION: image2vector

def image2vector(image):
    """
    Argument:
    image -- a numpy array of shape (length, height, depth)
    
    Returns:
    v -- a vector of shape (length*height*depth, 1)
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    v = image.reshape((image.shape[0]*image.shape[1]*image.shape[2]), 1)
    
    ### END CODE HERE ###
    
    return v

In [15]:
# This is a 3 by 3 by 2 array, typically images will be (num_px_x, num_px_y,3) where 3 represents the RGB values
image = np.array([
       [[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]
])

print ("image2vector(image) = " + str(image2vector(image)))

image2vector(image) = [[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]


**Expected Output**: 

```python
image2vector(image) = [[ 0.67826139]
 [ 0.29380381]
 [ 0.90714982]
 [ 0.52835647]
 [ 0.4215251 ]
 [ 0.45017551]
 [ 0.92814219]
 [ 0.96677647]
 [ 0.85304703]
 [ 0.52351845]
 [ 0.19981397]
 [ 0.27417313]
 [ 0.60659855]
 [ 0.00533165]
 [ 0.10820313]
 [ 0.49978937]
 [ 0.34144279]
 [ 0.94630077]]
```

---
### 1.4 - Normalizing rows

Another common technique we use in Machine Learning and Deep Learning is to normalize our data. It often leads to a better performance because gradient descent converges faster after normalization. Normalization, in our case, means changing `x` to $ \frac{x}{\| x\|} $ (dividing each row vector of `x` by its norm).

For example, if $$x = 
\begin{bmatrix}
    0 & 3 & 4 \\
    2 & 6 & 4 \\
\end{bmatrix}\tag{3}$$ then $$\| x\| = np.linalg.norm(x, axis = 1, keepdims = True) = \begin{bmatrix}
    5 \\
    \sqrt{56} \\
\end{bmatrix}\tag{4} $$and        $$ x\_normalized = \frac{x}{\| x\|} = \begin{bmatrix}
    0 & \frac{3}{5} & \frac{4}{5} \\
    \frac{2}{\sqrt{56}} & \frac{6}{\sqrt{56}} & \frac{4}{\sqrt{56}} \\
\end{bmatrix}\tag{5}$$ 

<div class="alert alert-warning">
**NOTE:** You can divide matrices of different shapes and it works fine: this is called _broadcasting_. We'll cover that in the next section (1.5).
</div>

<div class="alert alert-info" markdown=1><h2> Exercise 6 </h2></div>

Implement `normalize_rows()` to normalize the rows of a matrix. After applying this function to an input matrix `x`, each row of `x` should be a vector of unit length (meaning length 1).

In [16]:
# GRADED FUNCTION: normalizeRows

def normalize_rows(x):
    """
    Implement a function that normalizes each row of the matrix x (to have unit length).
    
    Argument:
    x -- A numpy matrix of shape (n, m)
    
    Returns:
    x -- The normalized (by row) numpy matrix. You are allowed to modify x.
    """
    
    ### START CODE HERE ### (≈ 2 lines of code)
    # Compute x_norm as the norm 2 of x. Use np.linalg.norm(..., ord=2, axis=..., keepdims=True)
    x_norm = np.linalg.norm(x, ord=2, axis=1, keepdims=True)
    
    # Divide x by its norm.
    x = x / x_norm
    ### END CODE HERE ###

    return x

In [17]:
x = np.array([
    [0, 3, 4],
    [1, 6, 4]])
print("normalize_rows(x) = " + str(normalize_rows(x)))

normalize_rows(x) = [[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]


**Expected Output**: 

```python
normalizeRows(x) = [[ 0.          0.6         0.8       ]
 [ 0.13736056  0.82416338  0.54944226]]
```

<div class="alert alert-warning" markdown=1>
<p>**NOTE**: If you print `x.shape` and `x_norm.shape`, then re-run the above code-cell, you'll find that `x.shape != x_norm.shape` &ndash; that's odd... </p>

<p>However, let's recall how `x_norm` works &ndash; it finds the norm of `x` &ndash; so `x_norm` has the same number of rows, but only one column (note that `x.shape[0] == x_norm.shape[0]`).</p>

<p>Hmm... that still doesn't answer the question of how was `x / x_norm` a valid operation? Well, it's _broadcasting_ and it's the next section! :)</p>
</div>

---
### 1.5 - Broadcasting and the softmax function ####
A very important concept to understand in numpy is "broadcasting". It is very useful for performing mathematical operations between arrays of different shapes. For the full details on broadcasting, you can read the official [broadcasting documentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html).

<div class="alert alert-info" markdown=1><h2> Exercise 7 </h2></div>

Implement the softmax function, using `numpy`. Think of the softmax as a normalizing function &ndash; this is useful especially when you algorithm needs to clasify two or more calsses.

**Instructions**:
- $ \text{for } x \in \mathbb{R}^{1\times n} \text{,     } softmax(x) = softmax(\begin{bmatrix}
    x_1  &&
    x_2 &&
    ...  &&
    x_n  
\end{bmatrix}) = \begin{bmatrix}
     \frac{e^{x_1}}{\sum_{j}e^{x_j}}  &&
    \frac{e^{x_2}}{\sum_{j}e^{x_j}}  &&
    ...  &&
    \frac{e^{x_n}}{\sum_{j}e^{x_j}} 
\end{bmatrix} $ 

- $\text{for a matrix } x \in \mathbb{R}^{m \times n} \text{,  $x_{ij}$ maps to the element in the $i^{th}$ row and $j^{th}$ column of $x$, thus we have: }$  $$softmax(x) = softmax\begin{bmatrix}
    x_{11} & x_{12} & x_{13} & \dots  & x_{1n} \\
    x_{21} & x_{22} & x_{23} & \dots  & x_{2n} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    x_{m1} & x_{m2} & x_{m3} & \dots  & x_{mn}
\end{bmatrix} = \begin{bmatrix}
    \frac{e^{x_{11}}}{\sum_{j}e^{x_{1j}}} & \frac{e^{x_{12}}}{\sum_{j}e^{x_{1j}}} & \frac{e^{x_{13}}}{\sum_{j}e^{x_{1j}}} & \dots  & \frac{e^{x_{1n}}}{\sum_{j}e^{x_{1j}}} \\
    \frac{e^{x_{21}}}{\sum_{j}e^{x_{2j}}} & \frac{e^{x_{22}}}{\sum_{j}e^{x_{2j}}} & \frac{e^{x_{23}}}{\sum_{j}e^{x_{2j}}} & \dots  & \frac{e^{x_{2n}}}{\sum_{j}e^{x_{2j}}} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    \frac{e^{x_{m1}}}{\sum_{j}e^{x_{mj}}} & \frac{e^{x_{m2}}}{\sum_{j}e^{x_{mj}}} & \frac{e^{x_{m3}}}{\sum_{j}e^{x_{mj}}} & \dots  & \frac{e^{x_{mn}}}{\sum_{j}e^{x_{mj}}}
\end{bmatrix} = \begin{pmatrix}
    softmax\text{(first row of x)}  \\
    softmax\text{(second row of x)} \\
    ...  \\
    softmax\text{(last row of x)} \\
\end{pmatrix} $$

In [18]:
def softmax(x):
    """Calculates the softmax for each row of the input x.

    Your code should work for a row vector and also for matrices of shape (n, m).

    Argument:
    x -- A numpy matrix of shape (n,m)

    Returns:
    s -- A numpy matrix equal to the softmax of x, of shape (n,m)
    """
    
    ### START CODE HERE ### (≈ 3 lines of code)
    # Apply exp() element-wise to x. Use np.exp(...).
    x_exp = np.exp(x)

    # Create a vector x_sum that sums each row of x_exp. Use np.sum(..., axis=1, keepdims=True).
    x_sum = np.sum(x_exp, axis=1, keepdims=True)
 
    
    # Compute softmax(x) by dividing x_exp by x_sum. It should automatically use numpy broadcasting.
    s = x_exp / x_sum

    ### END CODE HERE ###
    
    return s

In [19]:
x = np.array([
    [9, 2, 5, 0, 0],
    [7, 5, 0, 0 ,0]])
print("softmax(x) = " + str(softmax(x)))

softmax(x) = [[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]


**Expected Output**:

```python
softmax(x) = [[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]
```

<div class="alert alert-warning" markdown=1>
**NOTE**: If you take a look at `x_exp.shape`, `x_sum.shape`, and `s.shape` and rerun the code-cell above, you'll see what we saw 2 sections ago. Their shapes are unequal! However, if we take a look at `x_exp.shape[0]`, `x_sum.shape[0]`, and `s.shape[0]`, they all match. :D Like it has previously, this all works because of _broadcasting_. 
</div>

<div class="alert alert-success" markdown=1>**Awesome!** You've made it through Section 1 of this assignment. You should have a pretty good understanding of Python, `numpy`, and are familiar with a few useful functions that you'll be using throughout this course and in your graduate studies. </div>

<div class="alert alert-danger" markdown=1><p>**What to remember:**</p>
    <ul>
        <li>`np.exp` works for any `np.array` and applies the exponential function to every real-valued number</li>
        <li>the sigmoid function and its gradient</li>
        <li>`image2vector` is commonly used in deep learning</li>
        <li>`np.reshape` is widely used. Keeping your matrix/vector shapes straight &ndash; this will help alleviate quite a few bugs you'll run in to</li>
        <li>`numpy` has some rather efficient built-in functions</li>
        <li>_broadcasting_ is wonderful</li>
    </ul>
</div>

---
## 2 - Vectorization

In machine learning, you'll be dealing with very large datasets &ndash; because of this fact, it's paramount that you use computationally-optimal functions otherwise this will become a huge bottleneck in your pipeline, resulting in a model that **_might_** fully run before the midterm (okay, a little hyperbole, but all to make a point).

One of the powers on `numpy` is the use of vectorization. Avoiding a discussion on processor architecture, this speedup comes from giving a highly predictable workload to your processor.

We'll display some of the benefits of vectorization in terms of speedup below. Try to determine the differences between inner, outer, and elementwise products.

In [20]:
import time

x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### CLASSIC DOT PRODUCT OF VECTORS IMPLEMENTATION ###
tic = time.time()
dot = 0
for i in range(len(x1)):
    dot+= x1[i] * x2[i]
classic_dot = (time.time() - tic) * 1000
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(classic_dot) + "ms")

### CLASSIC OUTER PRODUCT IMPLEMENTATION ###
tic = time.time()
outer = np.zeros((len(x1),len(x2))) # we create a len(x1)*len(x2) matrix with only zeros
for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i,j] = x1[i] * x2[j]

classic_outer = (time.time() - tic) * 1000
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(classic_outer) + "ms")

### CLASSIC ELEMENTWISE IMPLEMENTATION ###
tic = time.time()
mul = np.zeros(len(x1))

for i in range(len(x1)):
    mul[i] = x1[i] * x2[i]
    
classic_mul = (time.time() - tic) * 1000
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(classic_mul) + "ms")

### CLASSIC GENERAL DOT PRODUCT IMPLEMENTATION ###
W = np.random.rand(3,len(x1)) # Random 3*len(x1) numpy array
tic = time.time()
gdot = np.zeros(W.shape[0])
for i in range(W.shape[0]):
    for j in range(len(x1)):
        gdot[i] += W[i,j] * x1[j]
        
classic_gdot = (time.time() - tic) * 1000
print ("gdot = " + str(gdot) + "\n ----- Computation time = " + str(classic_gdot) + "ms")

dot = 278
 ----- Computation time = 0.15282630920410156ms
outer = [[81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [63. 14. 14. 63.  0. 63. 14. 35.  0.  0. 63. 14. 35.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0

In [21]:
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### VECTORIZED DOT PRODUCT OF VECTORS ###
tic = time.time()
dot = np.dot(x1, x2)
numpy_dot = (time.time() - tic) * 1000
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(numpy_dot) + "ms")

### VECTORIZED OUTER PRODUCT ###
tic = time.time()
outer = np.outer(x1, x2)
numpy_outer = (time.time() - tic) * 1000
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(numpy_outer) + "ms")

### VECTORIZED ELEMENTWISE MULTIPLICATION ###
tic = time.time()
mul = np.multiply(x1, x2)
numpy_mul = (time.time() - tic) * 1000
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(numpy_mul) + "ms")

### VECTORIZED GENERAL DOT PRODUCT ###
tic = time.time()
dot = np.dot(W, x1)
numpy_gdot = (time.time() - tic) * 1000
print ("gdot = " + str(dot) + "\n ----- Computation time = " + str(numpy_gdot) + "ms")

dot = 278
 ----- Computation time = 0.12493133544921875ms
outer = [[81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [63 14 14 63  0 63 14 35  0  0 63 14 35  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
 ----- Computation time = 0.12803077697753906ms
elementwise multiplication = [81  4 10  0  0 63 10  0  0  0 81  4 25  0  0]
 ----- Computation time = 0.14781951904296875ms
gdot = [ 8.2586406  20.1103097  24.898014

Just to be verbose, here are the outcomes as their logged from the previous two code-cells.

In [22]:
times = [(classic_dot, numpy_dot), (classic_outer, numpy_outer), (classic_mul, numpy_mul), (classic_gdot, numpy_gdot)]
for act, mode in zip(["dot", "outer", "mul", "gdot"], times):
    print(act)
    print("  classic : {:1.8f}ms".format(mode[0]))
    print("  numpy   : {:1.8f}ms".format(mode[1]))

dot
  classic : 0.15282631ms
  numpy   : 0.12493134ms
outer
  classic : 0.26202202ms
  numpy   : 0.12803078ms
mul
  classic : 0.12969971ms
  numpy   : 0.14781952ms
gdot
  classic : 0.36811829ms
  numpy   : 57.76214600ms


As you may have noticed, the vectorized implementation is much cleaner and more efficient (especially for large inputs). For larger vectors/matrices, the differences in running time become more noticeable.

<div class="alert alert-warning" markdown=1>**Note** that `np.dot` performs a matrix-matrix or matrix-vector multiplication. This is different from `np.multiply` and the `*` operator (which is equivalent to  `.*` in Matlab/Octave), which performs an element-wise multiplication (hadamard product).</div>

---
### 2.1 Implement the L1 and L2 loss functions

<div class="alert alert-info" markdown=1><h2> Exercise 8 </h2></div>

Implement the `numpy` vectorized version of the `L1 loss`. You may find the function `abs(x)` (absolute value of x) useful.

**Reminder**:
- The loss is used to evaluate the performance of your model. The bigger your loss is, the more different your predictions ($ \hat{y} $) are from the true values ($y$). In deep learning, you use optimization algorithms like Gradient Descent to train your model and to minimize the cost.
- `L1 loss` is defined as:
$$\begin{align*} & L_1(\hat{y}, y) = \sum_{i=0}^m|y^{(i)} - \hat{y}^{(i)}| \end{align*}\tag{6}$$

In [23]:
# GRADED FUNCTION: L1

def L1(yhat, y):
    """
    Arguments:
    yhat -- vector of size m (predicted labels)
    y -- vector of size m (true labels)
    
    Returns:
    loss -- the value of the L1 loss function defined above
    """
    
    ### START CODE HERE ### (~1 line of code)
    loss = np.sum(abs(y - yhat))
    
    ### END CODE HERE ###
    
    return loss

In [24]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y    = np.array([1, 0, 0, 1, 1])
print("L1 = " + str(L1(yhat,y)))

L1 = 1.1


**Expected Output**:

```python
L1 = 1.1
```

<div class="alert alert-info" markdown=1><h2> Exercise 9 </h2></div>

Implement the `numpy` vectorized version of the `L2 loss`. There are several ways to implement L2 loss but `np.dot` may come in handy. As a reminder, if $x = [x_1, x_2, ..., x_n]$, then `np.dot(x, x)` = $\sum_{j=0}^n x_j^{2}$. 

- `L2 loss` is defined as $$\begin{align*} & L_2(\hat{y},y) = \sum_{i=0}^m(y^{(i)} - \hat{y}^{(i)})^2 \end{align*}\tag{7}$$

In [25]:
# GRADED FUNCTION: L2

def L2(yhat, y):
    """
    Arguments:
    yhat -- vector of size m (predicted labels)
    y -- vector of size m (true labels)
    
    Returns:
    loss -- the value of the L2 loss function defined above
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    loss = np.sum((y - yhat) ** 2)
    ### END CODE HERE ###
    
    return loss

In [26]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y    = np.array([1, 0, 0, 1, 1])
print("L2 = " + str(L2(yhat,y)))

L2 = 0.43


**Expected Output**:

```python
L2 = 0.43
```

<div class="alert alert-success" markdown=1>Congratulations on completing this assignment. We hope that this little warm-up exercise helps you in the future assignments, which will be more exciting and interesting!</div>

<div class="alert alert-danger" markdown=1><p>**What to remember:**</p>
    <ul>
        <li>Vectorization provides code clarity, for yourself and others.</li>
        <li>More importantly, vectorization provides computational efficiency.</li>
        <li>Your review of L1 and L2 Loss.</li>
        <li>Now, you're familiar with a number of `numpy` functions, such as `np.sum`, `np.dot`, `np.mutliply`, `np.maximum`, etc.</li>
    </ul>
</div>